---
- name: Unarchive the kafka bin that needs to be downloaded
  unarchive:
    src: "{{ kafka_archive }}"
    dest: /opt/
    remote_src: yes
    validate_certs: no
    list_files: yes
  register: archive_contents

- name: Move to kafka
  command: mv /opt/{{ archive_contents.files[0].split('/')[0] }} /opt/kafka

- name: Create the config file
  template:
    src: server.properties.j2
    dest: /opt/kafka/config/server.properties

- name: Create the service file
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
