---

- name: stop kafka
  shell: ps aux | grep kafka | grep -v grep | awk '{print $2}' | xargs -i kill -9 {}
  ignore_errors: yes

- name: Delete /opt/kafka
  file:
    state: absent
    path: /opt/kafka
  ignore_errors: yes
