---
- name: Delete /opt/kafka
  file:
    state: absent
    path: /opt/kafka
  ignore_errors: yes

- name: Delete /etc/systemd/system/kafka.service
  file:
    state: absent
    path: /etc/systemd/system/kafka.service
  ignore_errors: yes
